name: Build Chrome Extension

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create extension package
      run: |
        # Remove any development files that shouldn't be in the package
        rm -rf .github
        rm -f README.md

        # Create a zip file with all extension files
        zip -r fr-transaction-extension.zip \
          manifest.json \
          background.js \
          content.js \
          popup.html \
          popup.js \
          icons/*.png

    - name: Upload extension package
      uses: actions/upload-artifact@v4
      with:
        name: fr-transaction-extension
        path: fr-transaction-extension.zip

    - name: Create Release (on tag)
      id: create_release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Chrome extension package for ForgeRock Transaction ID Monitor

          ## Installation
          1. Download the `fr-transaction-extension.zip` file
          2. Extract the contents
          3. Open Chrome and go to `chrome://extensions/`
          4. Enable "Developer mode"
          5. Click "Load unpacked" and select the extracted folder
        draft: false
        prerelease: false

    - name: Upload Release Asset (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./fr-transaction-extension.zip
        asset_name: fr-transaction-extension.zip
        asset_content_type: application/zip